### ISSUE TITLE
Corrupt Beatmaps don't Show when rush is selected

### ISSUE THREAD

**Issue by HeyItsJinx** [Beamographic/rush#208] opened 2021-12-13 20:06 UTC

**Comment by HeyItsJinx** [comment] 2021-12-13 20:07
for my own reasons a lot of my maps are corrupt but i have to be in standard, mania, taiko or catch to see that they are grey meaning they are corrupt.

**Comment by LumpBloom7** [comment] 2021-12-13 20:25
Please provide us something more to work with in order to even investigate this, like log files.

**Comment by HeyItsJinx** [comment] 2021-12-13 22:05
> Please provide us something more to work with in order to even investigate this, like log files.

which log would be appropriate for this scenario of corrupt beatmaps?

**Comment by LumpBloom7** [comment] 2021-12-13 23:15
All of them if you wanna cover all bases.

**Comment by HeyItsJinx** [comment] 2021-12-14 10:52
[performance.log](https://github.com/Beamographic/rush/files/7710971/performance.log)
[runtime.log](https://github.com/Beamographic/rush/files/7710972/runtime.log)
[updater.log](https://github.com/Beamographic/rush/files/7710973/updater.log)
[database.log](https://github.com/Beamographic/rush/files/7710974/database.log)
[network.log](https://github.com/Beamographic/rush/files/7710975/network.log)

**Comment by LumpBloom7** [comment] 2021-12-14 11:02
Did you manage to reproduce the problem during that exact session the logs came from? 

From what I'm seeing, it looks like you've started the game after wiping your beatmaps, and did nothing else.

**Comment by HeyItsJinx** [comment] 2021-12-14 15:12
I went through them and just deleted a load of them that were corrupt, its not something i can "Re create". if i come accross another corrupt map ill update this post.

> Did you manage to reproduce the problem during that exact session the logs came from? The runtime logs seem to show that you've never even reached the main menu.
> 
> Running the game will always override the old log files. If you do run the game, you have to reproduce the problem in order for the logs to record what happened there.

**Comment by LumpBloom7** [comment] 2021-12-14 15:17
Will close this for now. Feel free to bump this issue when that happens.

**Closed by LumpBloom7** 2021-12-14 15:17 UTC
Labels: missing details
