### ISSUE TITLE
Graphical Error: Fever Bar

### ISSUE THREAD

**Issue by HeyItsJinx** [Beamographic/rush#171] opened 2021-08-01 12:08 UTC
Since latest update there is error with fever bar. nothing major or game just presenting weird (Cant find a way to upload screenshots so ill add another post with screenshot link)

**Comment by HeyItsJinx** [comment] 2021-08-01 12:08
https://ibb.co/XCFgBMv

**Comment by LumpBloom7** [comment] 2021-08-01 12:13
Seems likely that it is caused by the recent use of `LocalisableString` in `RollingCounter`, and the game is falling back to the default formatting.

I'll bump and release a hotfix build.

**Comment by LumpBloom7** [comment] 2021-08-01 12:58
Fixed in #172 and [hotfix released](https://github.com/Beamographic/rush/releases/tag/2021.801.0)

**Closed by LumpBloom7** 2021-08-01 12:58 UTC
Labels: area:UI
