### ISSUE TITLE
Cursor not disappearing when song is selected.

### ISSUE THREAD

**Issue by HeyItsJinx** [Beamographic/rush#168] opened 2021-07-22 11:07 UTC
When the map starts the cursor just stays on the screen. not very major but it kills the ocd

**Comment by LumpBloom7** [comment] 2021-07-23 15:23
As something to note, Rush doesn't provide a cursor to replace the default cursor, so unconditionally accepting positional input will lead to the cursor always being invisible. This could pose a UX problem for mouse users, since it is significantly harder to tell where the cursor is, when compared to only disappearing in certain areas, preventing/slowing them from clicking the pause button in the bottom right. 

Mania, ctb, and taiko only hides the default cursor within the playfield boundaries, which is likely due to the above consideration. (osu has a custom cursor)

**Comment by frenzibyte** [comment] 2021-07-24 04:12
I think what we have is consistent with all other rulesets as mentioned above, therefore I don't believe this to be an issue we should resolve here.

**Comment by LumpBloom7** [comment] 2021-07-24 08:03
Closing as this is an intended behavior. 

If it really bugs you, you could move the cursor to within the playfield to make it disappear.

**Closed by LumpBloom7** 2021-07-24 08:03 UTC
Labels: area:UI
